image:
  repository: clickhouse/clickhouse-server
  tag: "22.3"

storage:
  size: 200Gi

clickhouse:
  replicaCount: 1
  shardsCount: 1

resources:
  limits:
    cpu: 2
    memory: 8Gi
  requests:
    cpu: 1
    memory: 4Gi
